version: '3'
services:

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      ports:
        - "5432:5432"
        # (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: nginx-container
        build: ./nginx
        restart: always
        ports:
        - "8080:80"
        volumes:
        - web_data:/docker_web
        - ./log:/var/log/nginx
        depends_on:
        - web
        
    web:
        container_name: web-container
        build: ./web        
        restart: always
        entrypoint: /entrypoint.sh
        # command: uwsgi  --emperor uwsgi.ini
        command: uwsgi --ini uwsgi.ini
        ports:
        - "8002:8000"
        volumes:
        - web_data:/docker_web
        depends_on:
        - db

volumes:
    web_data:
    pgdata:

